## Logistic Regression for Multiclass Classification

In [2]:
## import necessary libraries
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [6]:
## create the dataset
from sklearn.datasets import make_classification
X, y = make_classification(n_samples = 1000 , n_features = 10 , n_informative= 3, n_classes = 3, random_state = 42)

In [7]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [8]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(multi_class='ovr')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)


/Users/amanverma/My PC/Coding/Github/dsml-projects/myenv/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/Users/amanverma/My PC/Coding/Github/dsml-projects/myenv/lib/python3.9/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights + intercept
/Users/amanverma/My PC/Coding/Github/dsml-projects/myenv/lib/python3.9/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights + intercept
/Users/amanverma/My PC/Coding/Github/dsml-projects/myenv/lib/python3.9/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights + intercept

In [9]:
## Performance matrics
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print( "Classification Report : \n\n\n" , classification_report(y_test, y_pred))
print( "\n\nConfusion Matrix : \n" , confusion_matrix(y_test, y_pred))
print( "\n\nAccuracy Score : \n" , accuracy_score(y_test, y_pred))

Classification Report : 


               precision    recall  f1-score   support

           0       0.70      0.77      0.73       103
           1       0.58      0.40      0.47        96
           2       0.71      0.86      0.78       101

    accuracy                           0.68       300
   macro avg       0.67      0.67      0.66       300
weighted avg       0.67      0.68      0.66       300



Confusion Matrix : 
 [[79 16  8]
 [31 38 27]
 [ 3 11 87]]


Accuracy Score : 
 0.68
